"""Add withdrawal rules fields and config

Revision ID: 06816d38434e
Revises: ec4a837250ff
Create Date: 2025-04-22 16:39:19.172380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06816d38434e'
down_revision = 'ec4a837250ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_withdrawal_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_withdrawal_date')

    # ### end Alembic commands ###
