"""Add Banner model

Revision ID: 073de63968b7
Revises: 926968c5cfb2
Create Date: 2025-05-09 20:18:38.513319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '073de63968b7'
down_revision = '926968c5cfb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_filename', sa.String(length=256), nullable=False),
    sa.Column('destination_url', sa.String(length=500), nullable=True),
    sa.Column('display_location', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_banner_is_active'), 'banner', ['is_active'], unique=False)
    op.drop_column('task', 'proof_type_required')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('proof_type_required', sa.VARCHAR(length=50), nullable=True))
    op.drop_index(op.f('ix_banner_is_active'), table_name='banner')
    op.drop_table('banner')
    # ### end Alembic commands ###
