"""Initial migration from current models

Revision ID: 10ab6e13cb4e
Revises: 
Create Date: 2025-05-12 21:36:44.228345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10ab6e13cb4e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_filename', sa.String(length=256), nullable=False),
    sa.Column('destination_url', sa.String(length=500), nullable=True),
    sa.Column('display_location', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_banner_is_active'), 'banner', ['is_active'], unique=False)
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('task_link', sa.String(length=500), nullable=True),
    sa.Column('reward_amount', sa.Float(), nullable=False),
    sa.Column('target_countries', sa.Text(), nullable=True),
    sa.Column('target_devices', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('image_filename', sa.String(length=256), nullable=True),
    sa.Column('is_daily', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone_number', sa.String(length=30), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('device', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('referral_code', sa.String(length=16), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_super_admin', sa.Boolean(), nullable=False),
    sa.Column('last_withdrawal_date', sa.DateTime(), nullable=True),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('referred_by_id', sa.Integer(), nullable=True),
    sa.Column('completed_task_count', sa.Integer(), nullable=False),
    sa.Column('telegram_username', sa.String(length=100), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['referred_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referral_code')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_full_name'), 'user', ['full_name'], unique=False)
    op.create_index(op.f('ix_user_is_verified'), 'user', ['is_verified'], unique=False)
    op.create_index(op.f('ix_user_telegram_username'), 'user', ['telegram_username'], unique=False)
    op.create_table('external_task_completion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('referrer_user_id', sa.Integer(), nullable=True),
    sa.Column('submitter_identifier', sa.String(length=120), nullable=True),
    sa.Column('submitted_proof', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('submission_timestamp', sa.DateTime(), nullable=True),
    sa.Column('processed_timestamp', sa.DateTime(), nullable=True),
    sa.Column('processed_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('screenshot_filename', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['processed_by_admin_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['referrer_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_name'), 'notification', ['name'], unique=False)
    op.create_index(op.f('ix_notification_timestamp'), 'notification', ['timestamp'], unique=False)
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('slug', sa.String(length=250), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('image_filename', sa.String(length=256), nullable=True),
    sa.Column('allow_comments', sa.Boolean(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_is_published'), 'post', ['is_published'], unique=False)
    op.create_index(op.f('ix_post_slug'), 'post', ['slug'], unique=True)
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    op.create_table('user_task_completion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('completion_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('withdrawal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('request_timestamp', sa.DateTime(), nullable=True),
    sa.Column('processed_timestamp', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('processed_by_admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['processed_by_admin_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['comment.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_timestamp'), 'comment', ['timestamp'], unique=False)
    op.create_table('referral_commission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referrer_id', sa.Integer(), nullable=False),
    sa.Column('referred_user_id', sa.Integer(), nullable=False),
    sa.Column('originating_completion_id', sa.Integer(), nullable=False),
    sa.Column('commission_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('creation_timestamp', sa.DateTime(), nullable=True),
    sa.Column('processed_timestamp', sa.DateTime(), nullable=True),
    sa.Column('processed_by_admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['originating_completion_id'], ['user_task_completion.id'], ),
    sa.ForeignKeyConstraint(['processed_by_admin_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['referred_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['referrer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('originating_completion_id')
    )
    op.create_index(op.f('ix_referral_commission_creation_timestamp'), 'referral_commission', ['creation_timestamp'], unique=False)
    op.create_index(op.f('ix_referral_commission_referred_user_id'), 'referral_commission', ['referred_user_id'], unique=False)
    op.create_index(op.f('ix_referral_commission_referrer_id'), 'referral_commission', ['referrer_id'], unique=False)
    op.create_index(op.f('ix_referral_commission_status'), 'referral_commission', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_referral_commission_status'), table_name='referral_commission')
    op.drop_index(op.f('ix_referral_commission_referrer_id'), table_name='referral_commission')
    op.drop_index(op.f('ix_referral_commission_referred_user_id'), table_name='referral_commission')
    op.drop_index(op.f('ix_referral_commission_creation_timestamp'), table_name='referral_commission')
    op.drop_table('referral_commission')
    op.drop_index(op.f('ix_comment_timestamp'), table_name='comment')
    op.drop_table('comment')
    op.drop_table('withdrawal')
    op.drop_table('user_task_completion')
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_index(op.f('ix_post_slug'), table_name='post')
    op.drop_index(op.f('ix_post_is_published'), table_name='post')
    op.drop_table('post')
    op.drop_index(op.f('ix_notification_timestamp'), table_name='notification')
    op.drop_index(op.f('ix_notification_name'), table_name='notification')
    op.drop_table('notification')
    op.drop_table('external_task_completion')
    op.drop_index(op.f('ix_user_telegram_username'), table_name='user')
    op.drop_index(op.f('ix_user_is_verified'), table_name='user')
    op.drop_index(op.f('ix_user_full_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('task')
    op.drop_index(op.f('ix_banner_is_active'), table_name='banner')
    op.drop_table('banner')
    # ### end Alembic commands ###
