# migrations/versions/1997b6350f1c_add_image_filename_to_task_model.py
"""Add image_filename to Task model

Revision ID: 1997b6350f1c
Revises: 1a2b3c4d5e6f # Assurez-vous que cet ID est correct pour la migration précédente
Create Date: 2025-04-24 15:28:35.272673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1997b6350f1c'
down_revision = '1a2b3c4d5e6f' # Assurez-vous que cet ID est correct pour la migration précédente
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Utilise batch_alter_table pour compatibilité SQLite
    with op.batch_alter_table('task', schema=None) as batch_op:
        # Ajout de server_default=None car nullable=True
        batch_op.add_column(sa.Column('image_filename', sa.String(length=256), nullable=True, server_default=None))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Utilise batch_alter_table pour compatibilité SQLite
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('image_filename')
    # ### end Alembic commands ###

