# migrations/versions/1b8360a6e188_set_pp364598_as_super_admin_after_registration.py
"""Set pp364598 as super admin after registration

Revision ID: 1b8360a6e188
Revises: 10ab6e13cb4e # <<< CORRIGÉ : Doit pointer vers la nouvelle migration initiale
Create Date: # Date de création originale de ce fichier
"""
from alembic import op
import sqlalchemy as sa
# Import pour l'update direct
from sqlalchemy.sql import table, column
from sqlalchemy import Boolean, String

# revision identifiers, used by Alembic.
revision = '1b8360a6e188'
down_revision = '10ab6e13cb4e' # <<< CORRIGÉ : Pointeur vers la migration "initial_migration_from_current_models"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    user_table = table('user',
        column('email', String),
        column('is_admin', Boolean),
        column('is_super_admin', Boolean)
    )

    op.execute(
        user_table.update().
        where(user_table.c.email == op.inline_literal('pp364598@gmail.com')).
        values(is_admin=op.inline_literal(True), is_super_admin=op.inline_literal(True))
    )
    print("INFO: Attempted to set pp364598@gmail.com as super admin.")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    user_table = table('user',
        column('email', String),
        column('is_admin', Boolean),
        column('is_super_admin', Boolean)
    )
    op.execute(
        user_table.update().
        where(user_table.c.email == op.inline_literal('pp364598@gmail.com')).
        values(is_admin=op.inline_literal(False), is_super_admin=op.inline_literal(False))
    )
    print("INFO: Attempted to remove super admin rights from pp364598@gmail.com during downgrade.")
    # ### end Alembic commands ###
