# migrations/versions/27d4780cb1bd_add_description_to_customscript_model.py
"""Add description to CustomScript model (column likely already created by initial migration)

Revision ID: 27d4780cb1bd
Revises: 123949fe00c3 # Pointeur vers la migration 'Set initial super admin account'
Create Date: # Votre date de création originale
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27d4780cb1bd'
down_revision = '123949fe00c3' # Doit pointer vers la migration 'Set initial super admin account'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # La colonne 'description' devrait déjà avoir été créée par la migration initiale
    # si app/models.py était à jour à ce moment-là.
    # Cette migration devient donc une étape vide pour maintenir la chaîne.
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Si la colonne a été créée par la migration initiale, la supprimer ici
    # pourrait être incorrect si on revient avant la migration initiale.
    # Pour plus de sécurité, on ne fait rien, ou on supprime conditionnellement.
    # Pour l'instant, on ne fait rien.
    pass
    # ### end Alembic commands ###
