# migrations/versions/34be3177cae7_add_telegram_username_and_is_verified_.py
"""Add telegram_username and is_verified to User

Revision ID: 34be3177cae7
Revises: 1997b6350f1c # <<< CORRECTION : Doit pointer vers la migration précédente (image_filename)
Create Date: 2025-04-25 XX:XX:XX # Date de création

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34be3177cae7' # <<< ID de ce fichier
down_revision = '1997b6350f1c' # <<< ID de la migration précédente (image_filename)
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telegram_username', sa.String(length=100), nullable=True, server_default=None))
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.create_index(batch_op.f('ix_user_is_verified'), ['is_verified'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_telegram_username'), ['telegram_username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_telegram_username'))
        batch_op.drop_index(batch_op.f('ix_user_is_verified'))
        batch_op.drop_column('is_verified')
        batch_op.drop_column('telegram_username')
    # ### end Alembic commands ###