# migrations/versions/926968c5cfb2_add_is_daily_to_task_model.py
"""Add is_daily to Task model

Revision ID: 926968c5cfb2
Revises: 34be3177cae7 # Assurez-vous que cet ID est celui de la migration précédente
Create Date: # Date de création par Alembic

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '926968c5cfb2'
down_revision = '34be3177cae7' # Vérifiez que c'est l'ID de la migration précédente
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        # <<< CORRECTION ICI : Ajout de server_default='0' >>>
        batch_op.add_column(sa.Column('is_daily', sa.Boolean(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('is_daily')
    # ### end Alembic commands ###