# migrations/versions/9888efdcb79b_add_parent_id_to_comment_for_replies.py
"""Add parent_id to Comment for replies

Revision ID: 9888efdcb79b  # <<< METTEZ L'ID DE CE FICHIER DE MIGRATION ICI
Revises: 0bd64ed3f23f    # <<< ID de la migration précédente (add_post_and_comment_models)
Create Date: 2025-05-10 HH:MM:SS.ffffff # Date de création

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9888efdcb79b'  # <<< METTEZ L'ID DE CE FICHIER DE MIGRATION ICI
down_revision = '0bd64ed3f23f'  # <<< ID de la migration précédente
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        # Le nom de la contrainte 'fk_comment_parent_id_comment' peut varier
        # Utilisez celui généré par batch_op.f si possible, sinon un nom explicite.
        batch_op.create_foreign_key(
            'fk_comment_parent_id_comment', # Nom de la contrainte
            'comment', # Table source (où se trouve la FK)
            ['parent_id'], # Colonne(s) source
            ['id'] # Colonne(s) cible dans la table 'comment'
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint('fk_comment_parent_id_comment', type_='foreignkey') # Utilisez le même nom de contrainte
        batch_op.drop_column('parent_id')
    # ### end Alembic commands ###