# migrations/versions/a59573f8f5f6_add_customscript_model_for_custom_head_.py
"""Add CustomScript model for custom head and footer scripts

Revision ID: a59573f8f5f6
Revises: 1b8360a6e188
Create Date: # Votre date de création originale pour ce fichier
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a59573f8f5f6'
down_revision = '1b8360a6e188' # Pointeur vers la migration 'set_pp364598_as_super_admin_after_'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_script',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('script_code', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=10), nullable=False),
    sa.Column('excluded_endpoints', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.false()),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name=op.f('uq_custom_script_name'))
    )
    with op.batch_alter_table('custom_script', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_custom_script_is_active'), ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('custom_script', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_custom_script_is_active'))
        # La contrainte unique est supprimée avec la table.
        # Si vous aviez besoin de la supprimer explicitement :
        # batch_op.drop_constraint(op.f('uq_custom_script_name'), type_='unique')

    op.drop_table('custom_script')
    # ### end Alembic commands ###