# migrations/versions/a59573f8f5f6_add_customscript_model_for_custom_head_.py
"""Add CustomScript model and effectively replaces SiteSetting logic

Revision ID: a59573f8f5f6
Revises: 1b8360a6e188 # <<< CORRIGÉ : Pointeur vers la migration 'set_pp364598_as_super_admin_after_'
Create Date: 2025-05-13 12:16:53.501651 # La date de création reste celle générée par Alembic

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a59573f8f5f6'
down_revision = '1b8360a6e188' # <<< CORRIGÉ : Pointeur vers la migration 'set_pp364598_as_super_admin_after_'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_script',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('script_code', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=10), nullable=False),
    sa.Column('excluded_endpoints', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.false()),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name=op.f('uq_custom_script_name'))
    )
    with op.batch_alter_table('custom_script', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_custom_script_is_active'), ['is_active'], unique=False)

    # On ne supprime plus 'site_setting' ici car la migration qui la créait (5777...) est supposée être supprimée.
    # Si 'site_setting' existe toujours dans votre base de données de production (Render)
    # à cause d'un déploiement précédent, il faudra peut-être une migration séparée pour la supprimer
    # ou la supprimer manuellement sur Render si c'est plus simple.
    # Pour l'instant, on se concentre sur la création de 'custom_script'.
    # op.drop_table('site_setting') # Commenté pour éviter erreur si la table n'existe pas
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('custom_script', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_custom_script_is_active'))

    op.drop_table('custom_script')

    # On ne recrée plus 'site_setting' ici car on considère que la migration 5777... est supprimée.
    # op.create_table('site_setting',
    # sa.Column('id', sa.INTEGER(), nullable=False),
    # sa.Column('custom_head_scripts', sa.TEXT(), nullable=True),
    # sa.Column('custom_footer_scripts', sa.TEXT(), nullable=True),
    # sa.Column('last_updated', sa.DATETIME(), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # ### end Alembic commands ###
