"""Add screenshot_filename to ExternalTaskCompletion

Revision ID: c4b6ff324e0b
Revises: 823ec9b58349
Create Date: 2025-04-22 19:04:14.773623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4b6ff324e0b'
down_revision = '823ec9b58349'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('external_task_completion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('screenshot_filename', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('external_task_completion', schema=None) as batch_op:
        batch_op.drop_column('screenshot_filename')

    # ### end Alembic commands ###
