"""Add referred_by_id and completed_task_count to User

Revision ID: d4ede12f590a
Revises: c4b6ff324e0b
Create Date: 2025-04-23 12:47:27.085810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4ede12f590a'
down_revision = 'c4b6ff324e0b' # Assurez-vous que cela pointe vers la bonne révision précédente
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - ADJUSTED ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        # Ajout de la colonne referred_by_id (nullable=True est OK)
        batch_op.add_column(sa.Column('referred_by_id', sa.Integer(), nullable=True))
        # Ajout de la colonne completed_task_count AVEC server_default='0'
        batch_op.add_column(sa.Column('completed_task_count', sa.Integer(), nullable=False, server_default='0'))
        # Création de la clé étrangère AVEC le nom explicite
        batch_op.create_foreign_key('fk_user_referred_by_id_user', 'user', ['referred_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - ADJUSTED ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        # Suppression de la contrainte en utilisant son nom
        batch_op.drop_constraint('fk_user_referred_by_id_user', type_='foreignkey')
        # Suppression des colonnes
        batch_op.drop_column('referred_by_id')
        batch_op.drop_column('completed_task_count')
    # ### end Alembic commands ###