"""Create ReferralCommission table

Revision ID: ed9f27dccec0
Revises: d4ede12f590a
Create Date: 2025-04-23 13:14:42.112995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed9f27dccec0'
down_revision = 'd4ede12f590a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referral_commission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referrer_id', sa.Integer(), nullable=False),
    sa.Column('referred_user_id', sa.Integer(), nullable=False),
    sa.Column('originating_completion_id', sa.Integer(), nullable=False),
    sa.Column('commission_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('creation_timestamp', sa.DateTime(), nullable=True),
    sa.Column('processed_timestamp', sa.DateTime(), nullable=True),
    sa.Column('processed_by_admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['originating_completion_id'], ['user_task_completion.id'], ),
    sa.ForeignKeyConstraint(['processed_by_admin_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['referred_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['referrer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('originating_completion_id')
    )
    with op.batch_alter_table('referral_commission', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_referral_commission_creation_timestamp'), ['creation_timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_referral_commission_referred_user_id'), ['referred_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_referral_commission_referrer_id'), ['referrer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_referral_commission_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('referral_commission', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_referral_commission_status'))
        batch_op.drop_index(batch_op.f('ix_referral_commission_referrer_id'))
        batch_op.drop_index(batch_op.f('ix_referral_commission_referred_user_id'))
        batch_op.drop_index(batch_op.f('ix_referral_commission_creation_timestamp'))

    op.drop_table('referral_commission')
    # ### end Alembic commands ###
